### **What is difference arnage and range functions.**

* range() : 
    1. Output Types :  Immutable sequences of integers.
    2. Data Types : Intgers Only 
    3. Usage : Loops, Iteration
    4. Example : range(start,stop, step)

* arange():
    1. Output Types: Numpy array (can be int or float)
    2. Data Types: Integers or floats
    3. Numberic Computation array generation
    4. Example : np.arange(start,stop,step)


In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
np.full((3,5),12)

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])

In [6]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.linspace(0,22,23)
# float data types , 
# np.linspace(start,stop,number_of_elements)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22.])

In [11]:
# Identity Diagonal matrix:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

## **List VS Numpy Array**

* List : 
    1. Contain Different data Typs like int, float, complex
    2.  Objects , Require Higher memory usage
    3. Sloawer interpreted per item
    4. No built in math operations

* NumPy Array :
    1. Homogeneity Maintain, Single Data types
    2. Memory less Required compare to list, Contiguous
    3. Speed : Vectorized, Much Faster
    4. Rich math/ statistics toolkits


In [15]:
# Element wise Operations
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
# Addition
c = a + b        
#  array([3, 5, 7])
# Multiplication
c = a * b        
# Exponent
c = a ** 2       
# array([2, 6, 12])
# array([1, 4, 9])
# Universal Functions
np.sin(a), np.exp(b)

(array([0.84147098, 0.90929743, 0.14112001]),
 array([ 7.3890561 , 20.08553692, 54.59815003]))